### ISSUE TITLE
Filename Praktikum 0: Git & Github.md

### ISSUE THREAD

**Issue by A21800086** [yysofiyan/PABWEB-D#3]
Filename "Praktikum 0: Git & Github.md" tidak terbaca oleh sistem operasi windows karena menggunakan karakter ":" (titik dua)

**Comment by yysofiyan** [comment]
Silahkan open Praktikum 0: Git & Github.md dengan menggunakan aplikasi visual studio code.

**Comment by A21800086** [comment]
> Silahkan open Praktikum 0: Git & Github.md dengan menggunakan aplikasi visual studio code.

Issuenya bukan tidak bisa di buka oleh text editor, tetapi ketika kita clone file tersebut auto terrename oleh windows jadi tanpa ":"

**Comment by yysofiyan** [comment]
Kebetulan beberapa file yang saya miliki memiliki nama yang mengandung` titik dua.` File ini biasanya terbentuk dari hasil screenshot/penamaan di Mac.  Masalahnya, Windows tidak bisa membaca file yang namanya mengandung` titik dua `karena `titik dua` adalah karakter yang `haram` dipakai sebagai `nama file` di `Windows`. 

Ok..,Saya akan 

> revisi file2.md 

yg mengandung  `titik dua`.

**Comment by A21800086** [comment]
Baik pak, terimakasih.
